In [1]:
import numpy as np


In [2]:
a = np.array([10,20,30])
b = np.array([3,5,7])

np.mod(a,b) # gives the remainder.

array([1, 0, 2])

In [3]:
np.remainder(a,b)

array([1, 0, 2])

In [6]:
a = np.array([2.0, 6.54, 143, 0.767, 65.542])
print(np.round(a))
print(np.round(a, decimals = 1))
print(np.round(a, decimals = -1))

[  2.   7. 143.   1.  66.]
[  2.    6.5 143.    0.8  65.5]
[  0.  10. 140.   0.  70.]


In [3]:
import numpy as np
a = np.array([-2.7, 3.6, -0.4, 0.9, 20])
print(np.floor(a))# -- goes to the nearest lower value.
print(np.ceil(a))#-- goes to the nearest higher value.

[-3.  3. -1.  0. 20.]
[-2.  4. -0.  1. 20.]


In [4]:
a = np.array([[79,65,45,55], [65,66,78,66], [77, 66,44,33]])

In [5]:
a

array([[79, 65, 45, 55],
       [65, 66, 78, 66],
       [77, 66, 44, 33]])

In [6]:
print(np.amin(a))

33


In [7]:
print(np.amin(a, axis=1)) # row wise minimum value

[45 65 33]


In [9]:
print(np.amin(a, axis = 0)) # colum wise minimum value

[65 65 44 33]


In [10]:
print(np.amax(a))


79


In [12]:
print(np.amax(a, axis=1)) # row wise maximun value

[79 78 77]


In [13]:
print(np.amax(a, axis = 0)) # column wise maximum value

[79 66 78 66]


In [14]:
a

array([[79, 65, 45, 55],
       [65, 66, 78, 66],
       [77, 66, 44, 33]])

In [15]:
#statistical function
a

array([[79, 65, 45, 55],
       [65, 66, 78, 66],
       [77, 66, 44, 33]])

In [22]:
print(np.median(a))
print(np.median(a, axis = 1)) #row wise median.
print(np.median(a, axis = 0)) #column wise median.

65.5
[60. 66. 55.]
[77. 66. 45. 55.]


In [24]:
print(np.mean(a))
print(np.mean(a, axis = 1)) # row wise mean
print(np.mean(a, axis = 0)) # column wise mean


61.583333333333336
[61.   68.75 55.  ]
[73.66666667 65.66666667 55.66666667 51.33333333]


In [25]:
a = np.array([1,2,3,4])

print(np.average(a))
print(np.mean(a))

2.5
2.5


In [26]:
a = np.array([1,2,3,4])
wts = np.array([4,3,2,1])
print(np.average(a))
print(np.mean(a))
print(np.average(a, weights= wts)) #(4X1+3X2+2X3+1X4)/(4+3+2+1) Weighted average is calculated

2.5
2.5
2.0


In [27]:
a

array([1, 2, 3, 4])

In [29]:
np.std(a)

1.118033988749895

In [30]:
np.var(a)

1.25

In [31]:
a = np.array([[79,65,45,55], [65,66,78,66], [77, 66,44,33]])

In [32]:
a

array([[79, 65, 45, 55],
       [65, 66, 78, 66],
       [77, 66, 44, 33]])

In [34]:
print(np.sort(a)) # row wise sorting

[[45 55 65 79]
 [65 66 66 78]
 [33 44 66 77]]


In [35]:
print(np.sort(a, axis = 1)) # row wise sorting, axis =1 is default

[[45 55 65 79]
 [65 66 66 78]
 [33 44 66 77]]


In [36]:
print(np.sort(a, axis = 0)) # row wise sorting, axis =1 is default

[[65 65 44 33]
 [77 66 45 55]
 [79 66 78 66]]


In [38]:
x=np.arange(9).reshape(3,3)

In [40]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
# i am looking for record where x>3
x[np.where(x>3)] # getting the record greater than 3 in flat mode.


array([4, 5, 6, 7, 8])

In [42]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
condition = np.mod(x,2)==0
# getting even numbers, remainder is zero.
np.extract(condition,x)

array([0, 2, 4, 6, 8])

In [ ]:
np.