
# Numpy - Numerical Python

In [7]:
import numpy as np
np.version.version

'1.24.2'

In [1]:
pip install numpy --upgrade


Note: you may need to restart the kernel to use updated packages.


In [1]:
pip list


Package                            Version
---------------------------------- -------------------
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 2.0.3
anaconda-project                   0.9.1
anyio                              2.2.0
appdirs                            1.4.4
argh                               0.26.2
argon2-cffi                        20.1.0
asgiref                            3.4.1
asn1crypto                         1.4.0
astroid                            2.5
astropy                            4.2.1
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              20.3.0
autopep8                           1.5.6
Babel                              2.9.0
backcall                           0.2.0
backports.functools-lru-cache      1.6.4
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.pos

In [10]:
sales = [4543,2233,4335, 3344, 4543, 6544, 3565, 3344, 6543, 6644, 8765, 3323, 5654, 3344, 5654, 7766]
profit = [454,233,443,566,777,677,555,766,455,554,665,455,345,766,444,567]

In [11]:
print(len(sales))
print(len(profit))


16
16


In [6]:
profit/sales


TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [8]:
profitratio = []
for i in range(0, len(sales)):
    profitratio.append(profit[i]/sales[i])
profitratio

[0.099933964340744,
 0.10434393193013883,
 0.10219146482122261,
 0.16925837320574164,
 0.17103235747303544,
 0.10345354523227383,
 0.15568022440392706,
 0.229066985645933,
 0.06953996637627999,
 0.08338350391330523,
 0.07586993725042784,
 0.13692446584411677,
 0.061018747789175806,
 0.229066985645933,
 0.07852847541563494,
 0.07301055884625289]

In [12]:
import numpy as np
sales_array = np.array(sales)

In [14]:
type(sales_array) # nd is n dimensional array, here the dimension is 1.

numpy.ndarray

In [15]:
profit_array = np.array(profit)

In [16]:
sales_array

array([4543, 2233, 4335, 3344, 4543, 6544, 3565, 3344, 6543, 6644, 8765,
       3323, 5654, 3344, 5654, 7766])

In [17]:
profit_array

array([454, 233, 443, 566, 777, 677, 555, 766, 455, 554, 665, 455, 345,
       766, 444, 567])

In [18]:
profit_array/sales_array

array([0.09993396, 0.10434393, 0.10219146, 0.16925837, 0.17103236,
       0.10345355, 0.15568022, 0.22906699, 0.06953997, 0.0833835 ,
       0.07586994, 0.13692447, 0.06101875, 0.22906699, 0.07852848,
       0.07301056])

In [19]:
# Here row by row execution is not happening. Numpy runs on c programmin.



In [28]:
from timeit import default_timer as timer
start = timer()
profitratio = []
for i in range(0, len(sales)):
    profitratio.append(profit[i]/sales[i])
profitratio
end = timer()
print((end- start))

0.0002714000002015382


In [29]:
from timeit import default_timer as timer
start = timer()
profit_array = np.array(profit)
end = timer()
print((end- start))

0.00018360000012762612


In [30]:
size = 1000000
l1 = range(size)
l2 = range(size)
a1 = np.arange(size) # arange is same as range function. arange mean array range.
a2 = np.arange(size) # 

In [32]:
start = timer()
result = [(x,y) for x,y in zip(l1,l2)]
print('Time taken by list operation')
end = timer()
print((end-start)*1000)


start = timer()
result = a1+a2
print("Time taken by Array")
end = timer()
print((end - start)*1000)

Time taken by list operation
591.1175000001094
Time taken by Array
62.79469999981302


In [33]:
cust = ['A1', 'A2', 'A3', 'A4']
order= [1,2,3,4]
for (c,o) in zip(cust, order): #zip function is used to iterate between the lists. 
    print("Hello", c, 'Your order id is:', o)

Hello A1 Your order id is: 1
Hello A2 Your order id is: 2
Hello A3 Your order id is: 3
Hello A4 Your order id is: 4


In [49]:
list1 = ['A',10, 10.5, True]


In [50]:
type(list1[0])

str

In [51]:
array1 = np.array(list1)

In [52]:
array1

array(['A', '10', '10.5', 'True'], dtype='<U32')

In [53]:
type(array1[2]) # when we have string in array all the elements of the array will take the string data types.

numpy.str_

In [54]:
list2 = [32, 3, 44, 34, 54]

In [55]:
list2*2 # duplicate the list

[32, 3, 44, 34, 54, 32, 3, 44, 34, 54]

In [56]:
array2 = np.array(list2)

In [57]:
array2*2

array([ 64,   6,  88,  68, 108])

In [58]:
list2

[32, 3, 44, 34, 54]

In [73]:
list2[0]=1000

In [74]:
list2

[1000, 3, 44, 34, 54]

In [59]:
list3 = list2.copy()


In [60]:
list3

[32, 3, 44, 34, 54]

In [62]:

list4 = list2[0:3]

#### 

In [63]:
list4

[32, 3, 44]

In [64]:
list4[0]= 100

In [67]:
list4# we updated the list4 but list 1 which is the parent list is not updated. List4 is the sliced list of list2.


[100, 3, 44]

In [68]:
list2

[32, 3, 44, 34, 54]

In [70]:
list3[0]= 200

In [71]:
list3

[200, 3, 44, 34, 54]

In [72]:
#All list is independent of each other



In [75]:
a1 =np.array(list2)

In [76]:
a1

array([1000,    3,   44,   34,   54])

In [78]:
a2 = a1.copy()

In [79]:
a2

array([1000,    3,   44,   34,   54])

In [80]:
a3 = a1[0:3]

In [81]:
a3

array([1000,    3,   44])

In [82]:
a1

array([1000,    3,   44,   34,   54])

In [83]:
a2

array([1000,    3,   44,   34,   54])

In [84]:
a3

array([1000,    3,   44])

In [85]:
a3[0] = 0

In [86]:
a3 # when we do any changes in the slices array , the parent array also get the changed.

array([ 0,  3, 44])

In [87]:
a1

array([ 0,  3, 44, 34, 54])

In [88]:
a2[0 ]= 34

In [91]:
a2 # When we do any change in in copy array the parent array is not changed.

array([34,  3, 44, 34, 54])

In [92]:
a1

array([ 0,  3, 44, 34, 54])

In [93]:
a1

array([ 0,  3, 44, 34, 54])

In [95]:
a1.dtype #dtype tells the data type of the array and is common for all elemnts.
#priority - string - float-int - boolean

dtype('int32')

In [96]:
a1.ndim

1

In [97]:
a1.shape

(5,)

In [98]:
sales_us = [4354,2342,5466,4533]
sales_eu = [5422,5666,5654,6743]
sales_jp = [4524,5646,5645,6656]

In [99]:
profit_us = [452,534,455,644]
profit_eu = [343,545,546,776]
profit_jp = [655,455,645,455]

In [101]:
sales_matrix = np.array([sales_us,sales_eu,sales_jp])

In [102]:
sales_matrix

array([[4354, 2342, 5466, 4533],
       [5422, 5666, 5654, 6743],
       [4524, 5646, 5645, 6656]])

In [103]:
sales_matrix.dtype

dtype('int32')

In [106]:

sales_matrix.ndim # ndim 2 means 2 dimension , row and columns.


2

In [107]:
sales_matrix.shape

(3, 4)

In [108]:
type(sales_matrix) # here n is 2 now.

numpy.ndarray

In [109]:
profit_matrix = np.array([profit_us, profit_eu,profit_jp])

In [110]:
profit_matrix

array([[452, 534, 455, 644],
       [343, 545, 546, 776],
       [655, 455, 645, 455]])

In [111]:
profit_matrix/sales_matrix

array([[0.10381259, 0.22801025, 0.08324186, 0.14206927],
       [0.06326079, 0.09618779, 0.0965688 , 0.11508231],
       [0.14478338, 0.08058803, 0.11426041, 0.06835938]])

In [113]:
profit_matrix

array([[452, 534, 455, 644],
       [343, 545, 546, 776],
       [655, 455, 645, 455]])

In [115]:
profit_matrix[1,2] #row no1 - index no 0, row nu

546

In [116]:
profit_matrix[0:2, 2:4]

array([[455, 644],
       [546, 776]])

In [117]:
profit_matrix[:, 2:4]

array([[455, 644],
       [546, 776],
       [645, 455]])

In [118]:
profit_matrix

array([[452, 534, 455, 644],
       [343, 545, 546, 776],
       [655, 455, 645, 455]])

In [120]:
rdict = {"US":0, "EU":1, "JP":2}
qdict = {"Q1":0, "Q2":1, "Q3":2, "Q4":3}

In [121]:
profit_matrix

array([[452, 534, 455, 644],
       [343, 545, 546, 776],
       [655, 455, 645, 455]])

In [122]:
profit_matrix[rdict['US']][qdict["Q3"]]

455

In [123]:
profit_matrix[0,2]

455

In [124]:
profit_matrix[0][2]

455

In [125]:
a = np.arange(1,21)

In [126]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [127]:
#Here i want to make 'a'which is  1d array to matrix taking 5 elemrnt in each row.


In [128]:
np.reshape(a,(4,5)) # here it is row by row

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [129]:
np.reshape(a,(4,5), 'F') # here it is column by column, F is taken from fortrane programming language.

array([[ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19],
       [ 4,  8, 12, 16, 20]])

In [130]:
np.reshape(a,(4,5), 'C') # here it is row by row. C is default mode. C means it is taken from C programming

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [131]:
np.reshape(a,(10,2), 'C')

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [132]:
import numpy as np
gp = np.array([[76,55,43,44], [54,66,55,34], [66,77,66,55]])

In [133]:
gp

array([[76, 55, 43, 44],
       [54, 66, 55, 34],
       [66, 77, 66, 55]])

In [135]:
b = gp.T

In [136]:
b

array([[76, 54, 66],
       [55, 66, 77],
       [43, 55, 66],
       [44, 34, 55]])

In [137]:
for x in np.nditer(b):
    print(x)

76
55
43
44
54
66
55
34
66
77
66
55


In [138]:
#concatenate

gp1 = np.array([[79,44,55,44],[34,54,43,67], [46, 65,53,35]])
gp2 = np.array([[45, 56, 65,45],[34,45,12,54], [44,45,12,45]])

In [139]:
gp1



array([[79, 44, 55, 44],
       [34, 54, 43, 67],
       [46, 65, 53, 35]])

In [140]:
gp2

array([[45, 56, 65, 45],
       [34, 45, 12, 54],
       [44, 45, 12, 45]])

In [142]:
np.concatenate((gp1,gp2), axis = 0)

array([[79, 44, 55, 44],
       [34, 54, 43, 67],
       [46, 65, 53, 35],
       [45, 56, 65, 45],
       [34, 45, 12, 54],
       [44, 45, 12, 45]])

In [143]:
np.concatenate((gp1,gp2), axis = 1)

array([[79, 44, 55, 44, 45, 56, 65, 45],
       [34, 54, 43, 67, 34, 45, 12, 54],
       [46, 65, 53, 35, 44, 45, 12, 45]])

In [144]:
np.stack((gp1,gp2), axis=0)

array([[[79, 44, 55, 44],
        [34, 54, 43, 67],
        [46, 65, 53, 35]],

       [[45, 56, 65, 45],
        [34, 45, 12, 54],
        [44, 45, 12, 45]]])

In [147]:
np.stack((gp1,gp2), axis = 1) # 1st row of 1st matrix, and 1st row of 2nd matrix.

array([[[79, 44, 55, 44],
        [45, 56, 65, 45]],

       [[34, 54, 43, 67],
        [34, 45, 12, 54]],

       [[46, 65, 53, 35],
        [44, 45, 12, 45]]])

In [148]:
np.hstack((gp1,gp2)) # This output is same as np.concatenate((gp1,gp2), axis = 1)

array([[79, 44, 55, 44, 45, 56, 65, 45],
       [34, 54, 43, 67, 34, 45, 12, 54],
       [46, 65, 53, 35, 44, 45, 12, 45]])

In [149]:
np.concatenate((gp1,gp2), axis = 1)

array([[79, 44, 55, 44, 45, 56, 65, 45],
       [34, 54, 43, 67, 34, 45, 12, 54],
       [46, 65, 53, 35, 44, 45, 12, 45]])

In [151]:
np.vstack((gp1,gp2)) # This output is same as np.concatenate((gp1,gp2), axis = 0)

array([[79, 44, 55, 44],
       [34, 54, 43, 67],
       [46, 65, 53, 35],
       [45, 56, 65, 45],
       [34, 45, 12, 54],
       [44, 45, 12, 45]])

In [152]:
 np.concatenate((gp1,gp2), axis = 0)

array([[79, 44, 55, 44],
       [34, 54, 43, 67],
       [46, 65, 53, 35],
       [45, 56, 65, 45],
       [34, 45, 12, 54],
       [44, 45, 12, 45]])

In [4]:
import numpy as np

In [2]:
gp = np.array([[79,62,33,45], [54,66,77,65]])

In [3]:
gp

array([[79, 62, 33, 45],
       [54, 66, 77, 65]])

In [4]:
np.append(gp, [67,32,54,76])# It flattened the matrix to vector. Single row 

array([79, 62, 33, 45, 54, 66, 77, 65, 67, 32, 54, 76])

In [5]:
gp = np.array([[79,62,33,45], [54,66,77,65]])
gp = np.append(gp, [[67,32,54,76]], axis = 0)

In [6]:
import numpy as np
gp

array([[79, 62, 33, 45],
       [54, 66, 77, 65],
       [67, 32, 54, 76]])

In [8]:
gp = np.array([[79,62,33,45], [54,66,77,65]])
np.append(gp, [[67,32,54,76]], axis = 1)      # Since axis=1 is size by size concatenation so for 2 row we should have 
#2 rows to append.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [9]:
gp = np.array([[79,62,33,45], [54,66,77,65]])
np.append(gp, [[67,32,54,76],[54,24,65,43]], axis = 1)

array([[79, 62, 33, 45, 67, 32, 54, 76],
       [54, 66, 77, 65, 54, 24, 65, 43]])

In [10]:
gp

array([[79, 62, 33, 45],
       [54, 66, 77, 65]])

In [12]:
gp

array([[79, 62, 33, 45],
       [54, 66, 77, 65],
       [67, 32, 54, 76]])

In [13]:
np.insert(gp, 3, [30,20]) #Here the elements are added to the 3rd position and then the other elements from the matrix 
#is followed Also the matrix get flattened. 

array([79, 62, 33, 30, 20, 45, 54, 66, 77, 65, 67, 32, 54, 76])

In [14]:
#we want to add some element at the row or column.

gp

array([[79, 62, 33, 45],
       [54, 66, 77, 65],
       [67, 32, 54, 76]])

In [16]:
np.insert(gp,1,[30], axis = 0) # ROW at index number 1 is added. If we give single value, it will replicate.and

array([[79, 62, 33, 45],
       [30, 30, 30, 30],
       [54, 66, 77, 65],
       [67, 32, 54, 76]])

In [18]:
np.insert(gp,1,[30,32,22,21], axis = 0) # If we give the value as per the matrix numpy will add the same values.


array([[79, 62, 33, 45],
       [30, 32, 22, 21],
       [54, 66, 77, 65],
       [67, 32, 54, 76]])

In [19]:
gp

array([[79, 62, 33, 45],
       [54, 66, 77, 65],
       [67, 32, 54, 76]])

In [21]:
np.insert(gp,1,[30,32,22], axis = 1) 
# Column is added.

array([[79, 30, 62, 33, 45],
       [54, 32, 66, 77, 65],
       [67, 22, 32, 54, 76]])

In [22]:
gp

array([[79, 62, 33, 45],
       [54, 66, 77, 65],
       [67, 32, 54, 76]])

In [24]:
#delete
np.delete(gp,3) # Here row1 index 3 is deleted. here we have not mentioned any axis.

array([79, 62, 33, 54, 66, 77, 65, 67, 32, 54, 76])

In [25]:
gp

array([[79, 62, 33, 45],
       [54, 66, 77, 65],
       [67, 32, 54, 76]])

In [26]:
np.delete(gp,1, axis = 1)

array([[79, 33, 45],
       [54, 77, 65],
       [67, 54, 76]])

In [27]:
np.delete(gp,1 , axis = 0)

array([[79, 62, 33, 45],
       [67, 32, 54, 76]])

In [28]:
gp

array([[79, 62, 33, 45],
       [54, 66, 77, 65],
       [67, 32, 54, 76]])

In [31]:
gp1 = np.delete(gp, np.s_[::2]) # This deleted 79,33,54,77,67,54

In [32]:
gp1

array([62, 45, 66, 65, 32, 76])

In [33]:
np.delete(gp, np.s_[::3])

array([62, 33, 54, 66, 65, 67, 54, 76])

In [34]:
a = np.array([74,33,45,45])
np.unique(a)

array([33, 45, 74])

In [35]:
np.unique(gp) # giving unique values but flattening.

array([32, 33, 45, 54, 62, 65, 66, 67, 76, 77, 79])

In [36]:
a

array([74, 33, 45, 45])

In [38]:
np.unique(a, return_index= True) # sorting the elements and giving the index number as well.

(array([33, 45, 74]), array([1, 2, 0], dtype=int64))

In [39]:
#Arithmetic Operations

gp1 = np.array([[54,33,44,33], [54,33,33,22]])
gp2 = np.array([[54,22,12,11], [76,55,33,22]])

In [40]:
gp1

array([[54, 33, 44, 33],
       [54, 33, 33, 22]])

In [41]:
gp2

array([[54, 22, 12, 11],
       [76, 55, 33, 22]])

In [42]:
gp1+gp2

array([[108,  55,  56,  44],
       [130,  88,  66,  44]])

In [43]:
np.add(gp1,gp2)

array([[108,  55,  56,  44],
       [130,  88,  66,  44]])

In [45]:
gp1

array([[54, 33, 44, 33],
       [54, 33, 33, 22]])

In [46]:
gp2

array([[54, 22, 12, 11],
       [76, 55, 33, 22]])

In [44]:
np.subtract(gp1,gp2)

array([[  0,  11,  32,  22],
       [-22, -22,   0,   0]])

In [47]:
np.multiply(gp1,gp2)

array([[2916,  726,  528,  363],
       [4104, 1815, 1089,  484]])

In [48]:
np.divide(gp1,gp2)

array([[1.        , 1.5       , 3.66666667, 3.        ],
       [0.71052632, 0.6       , 1.        , 1.        ]])

In [49]:
np.round(np.divide(gp1,gp2))

array([[1., 2., 4., 3.],
       [1., 1., 1., 1.]])

In [50]:
np.power(gp1,2)

array([[2916, 1089, 1936, 1089],
       [2916, 1089, 1089,  484]], dtype=int32)

In [51]:
gp1

array([[54, 33, 44, 33],
       [54, 33, 33, 22]])

In [52]:
power = [1,2,3,4]

In [54]:
np.power(gp1,power) #here 1st column has raise to power1 , 2nd column has power raise to 2, third column has power raise
# 3 and fourth column raise to power 4.

array([[     54,    1089,   85184, 1185921],
       [     54,    1089,   35937,  234256]])