In [1]:
import pandas as pd


In [48]:
df = pd.read_excel('dataprep.xlsx')

In [44]:
df

Student_Id  Marks_10  Marks_12  Marks_Grad  State  Salary
0           1      45.0       NaN        56.0    1.0      10
1           2       NaN      65.0        67.0    1.0      12
2           3      54.0      68.0        57.0    0.0      14
3           4      89.0      88.0         NaN    NaN      18
4           5       NaN      87.0        84.0    1.0      21

In [6]:
#Import scikit learn
import numpy as np
from sklearn.impute import SimpleImputer # We prefer to use numpy arrays while we use scikit learn.


In [7]:
df

Student_Id  Marks_10  Marks_12  Marks_Grad  State  Salary
0           1      45.0       NaN        56.0    1.0      10
1           2       NaN      65.0        67.0    1.0      12
2           3      54.0      68.0        57.0    0.0      14
3           4      89.0      88.0         NaN    NaN      18
4           5       NaN      87.0        84.0    1.0      21

In [19]:
x = df.iloc[:,0:6].values

In [20]:
x

array([[ 1., 45., nan, 56.,  1., 10.],
       [ 2., nan, 65., 67.,  1., 12.],
       [ 3., 54., 68., 57.,  0., 14.],
       [ 4., 89., 88., nan, nan, 18.],
       [ 5., nan, 87., 84.,  1., 21.]])

In [11]:
import numpy as np # 1st step import numpy package
from sklearn.impute import SimpleImputer #2nd step to import sk learn packege
imp = SimpleImputer(missing_values=np.nan, strategy='mean')# i want to populate the entire null by mean..
imputer = imp.fit(x[:,1:5]) # i want to populate to column number 1 to 4. here i am fitting imp on my array
x[:,1:5] = imputer.transform(x[:,1:5]) #Overwriting the array with imputer, replacing the nan values.

In [13]:
pd.DataFrame(x) # Missing value is the mean of that column elements.

0          1     2     3     4     5
0  1.0  45.000000  77.0  56.0  1.00  10.0
1  2.0  62.666667  65.0  67.0  1.00  12.0
2  3.0  54.000000  68.0  57.0  0.00  14.0
3  4.0  89.000000  88.0  66.0  0.75  18.0
4  5.0  62.666667  87.0  84.0  1.00  21.0

In [16]:
# Here we will take the strategy as median

import numpy as np # 1st step import numpy package
from sklearn.impute import SimpleImputer #2nd step to import sk learn packege
imp = SimpleImputer(missing_values=np.nan, strategy='median')# i want to populate the entire null by mean..
imputer = imp.fit(x[:,1:5]) # i want to populate to column number 1 to 4. here i am fitting imp on my array
x[:,1:5] = imputer.transform(x[:,1:5]) #Overwriting the array with imputer, replacing the nan values.

In [17]:
pd.DataFrame(x) # Missing value is the median of that column elements.

0     1     2     3    4     5
0  1.0  45.0  77.5  56.0  1.0  10.0
1  2.0  54.0  65.0  67.0  1.0  12.0
2  3.0  54.0  68.0  57.0  0.0  14.0
3  4.0  89.0  88.0  62.0  1.0  18.0
4  5.0  54.0  87.0  84.0  1.0  21.0

In [22]:
# Here we will take care till 4th column and 

import numpy as np # 1st step import numpy package
from sklearn.impute import SimpleImputer #2nd step to import sk learn packege
imp = SimpleImputer(missing_values=np.nan, strategy='median')# i want to populate the entire null by mean..
imputer = imp.fit(x[:,1:4]) # i want to populate to column number 1 to 4. here i am fitting imp on my array
x[:,1:4] = imputer.transform(x[:,1:4]) #Overwriting the array with imputer, replacing the nan values.
# Here we populated for missing value treatment upto 4th column and 5th column will treated with mode.

In [23]:
x

array([[ 1. , 45. , 77.5, 56. ,  1. , 10. ],
       [ 2. , 54. , 65. , 67. ,  1. , 12. ],
       [ 3. , 54. , 68. , 57. ,  0. , 14. ],
       [ 4. , 89. , 88. , 62. ,  nan, 18. ],
       [ 5. , 54. , 87. , 84. ,  1. , 21. ]])

In [24]:
# Here we will  

import numpy as np # 1st step import numpy package
from sklearn.impute import SimpleImputer #2nd step to import sk learn packege
imp = SimpleImputer(missing_values=np.nan, strategy='most_frequent')# i want to populate the entire null by mean..
imputer = imp.fit(x[:,4:5]) # i want to populate to column number 1 to 4. here i am fitting imp on my array
x[:,4:5] = imputer.transform(x[:,4:5]) #Overwriting the array with imputer, replacing the nan values.

#most frequent = mode.

In [25]:
x

array([[ 1. , 45. , 77.5, 56. ,  1. , 10. ],
       [ 2. , 54. , 65. , 67. ,  1. , 12. ],
       [ 3. , 54. , 68. , 57. ,  0. , 14. ],
       [ 4. , 89. , 88. , 62. ,  1. , 18. ],
       [ 5. , 54. , 87. , 84. ,  1. , 21. ]])

In [30]:
df1 = df

In [32]:
df1['Marks_10'] = df['Marks_10'].fillna(df1['Marks_10'].mean()) # I am using Dataframe directly.

In [33]:
df1

Student_Id   Marks_10  Marks_12  Marks_Grad  State  Salary
0           1  45.000000       NaN        56.0    1.0      10
1           2  62.666667      65.0        67.0    1.0      12
2           3  54.000000      68.0        57.0    0.0      14
3           4  89.000000      88.0         NaN    NaN      18
4           5  62.666667      87.0        84.0    1.0      21

In [34]:
df1['Marks_12'] = df['Marks_12'].fillna(df1['Marks_12'].median())

In [35]:
df1

Student_Id   Marks_10  Marks_12  Marks_Grad  State  Salary
0           1  45.000000      77.5        56.0    1.0      10
1           2  62.666667      65.0        67.0    1.0      12
2           3  54.000000      68.0        57.0    0.0      14
3           4  89.000000      88.0         NaN    NaN      18
4           5  62.666667      87.0        84.0    1.0      21

In [36]:
df1['Marks_Grad'] = df['Marks_Grad'].fillna(df1['Marks_Grad'].median())

In [37]:
df1

Student_Id   Marks_10  Marks_12  Marks_Grad  State  Salary
0           1  45.000000      77.5        56.0    1.0      10
1           2  62.666667      65.0        67.0    1.0      12
2           3  54.000000      68.0        57.0    0.0      14
3           4  89.000000      88.0        62.0    NaN      18
4           5  62.666667      87.0        84.0    1.0      21

In [38]:
df1['State'] = df['State'].fillna(df1['State'].median()) 

In [39]:
df1

Student_Id   Marks_10  Marks_12  Marks_Grad  State  Salary
0           1  45.000000      77.5        56.0    1.0      10
1           2  62.666667      65.0        67.0    1.0      12
2           3  54.000000      68.0        57.0    0.0      14
3           4  89.000000      88.0        62.0    1.0      18
4           5  62.666667      87.0        84.0    1.0      21

In [45]:
df

Student_Id  Marks_10  Marks_12  Marks_Grad  State  Salary
0           1      45.0       NaN        56.0    1.0      10
1           2       NaN      65.0        67.0    1.0      12
2           3      54.0      68.0        57.0    0.0      14
3           4      89.0      88.0         NaN    NaN      18
4           5       NaN      87.0        84.0    1.0      21

In [46]:
# K- nearest Neighbour Imputation

from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=2)
df = imputer.fit_transform(df)

In [47]:
df

array([[ 1. , 45. , 66.5, 56. ,  1. , 10. ],
       [ 2. , 49.5, 65. , 67. ,  1. , 12. ],
       [ 3. , 54. , 68. , 57. ,  0. , 14. ],
       [ 4. , 89. , 88. , 75.5,  1. , 18. ],
       [ 5. , 71.5, 87. , 84. ,  1. , 21. ]])

In [49]:
df

Student_Id  Marks_10  Marks_12  Marks_Grad  State  Salary
0           1      45.0       NaN        56.0    1.0      10
1           2       NaN      65.0        67.0    1.0      12
2           3      54.0      68.0        57.0    0.0      14
3           4      89.0      88.0         NaN    NaN      18
4           5       NaN      87.0        84.0    1.0      21

In [50]:
# K- nearest Neighbour Imputation

from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=1)
df = imputer.fit_transform(df)

In [51]:
df

array([[ 1., 45., 68., 56.,  1., 10.],
       [ 2., 54., 65., 67.,  1., 12.],
       [ 3., 54., 68., 57.,  0., 14.],
       [ 4., 89., 88., 84.,  1., 18.],
       [ 5., 89., 87., 84.,  1., 21.]])